Ausgewogenere Schwierigkeit bei Klammer-Entfernen-Aufgabe
fmidue/logic-tasks pull request #67
Opened 2023-12-11 15:04 UTC by nimec01

Ich habe mich mal an der Umsetzung eines Filters hinsichtlich #65 probiert. Anhand des `minUniqueOperators` Wertes in `SuperfluousBracketsConfig` kann man eine Mindestanzahl an Operatoren festlegen. Ich habe zwei neue Testfälle erstellt, die soweit auch erfolgreich absolviert werden. 

Gibt es für mich auch eine Möglichkeit, lokal eine Aufgabe zu generieren und diese in der Konsole ausgeben zu lassen? 

Des Weiteren ist mir aufgefallen, dass `stack test` bei mir immer wieder mal bei unterschiedlichen Testfällen hängen bleibt (auch unabhängig von meinen Änderungen). Ist das ein Phänomen, das nur bei mir auftritt?

Hier ist ein Output von einem dieser Fälle:
```
logic-tasks> test (suite: src-test)

Formula
  genValidBoundsClause
    should generate valid bounds [✔]
      +++ OK, passed 100 tests.     
  genValidBoundsCnf
    should generate valid bounds [✔]
      +++ OK, passed 1000 tests.
  genLiteral
    should throw an error when called with the empty list [✔]
    should generate a random literal from the given char list [✔]     
      +++ OK, passed 100 tests; 19 discarded.
  genClause
    should return the empty Clause when called with the empty list [✔]
      +++ OK, passed 100 tests.
    should return the empty Clause when called with invalid boundaries [✔]
      +++ OK, passed 100 tests; 15 discarded.
    should generate a random clause of the correct length if given valid parameters [✔]
      +++ OK, passed 100 tests.
  genCnf
    should return the empty conjunction when called with the empty list [✔]
      +++ OK, passed 100 tests.
    should generate a random cnf formula with a correct amount of clauses if given valid parameters [✔]
      +++ OK, passed 100 tests.
    should generate a random cnf formula with the correct clause length if given valid parameters [✔]     
      +++ OK, passed 100 tests.
LegalCNF
  validBoundsLegalCNF
    produces a valid config [✔]
      +++ OK, passed 1000 tests.
  invalidBoundsLegalCNF
    produces a valid config [‐]
      # PENDING: No reason given
  genIllegalSynTree
    the syntax Tree are not CNF syntax tree [✔]     
      +++ OK, passed 100 tests.
  judgeCnfSynTree
    is reasonably implemented [✔]     
      +++ OK, passed 100 tests.
  generateLegalCNFInst
    all of the formulas in the wrong serial should not be Cnf [45/100]
```

2023-12-12 10:57 UTC, jvoigtlaender commented
Betreffs lokalem Ausprobieren, das ist hier mal knapp beschrieben und lässt sich hoffentlich anwenden: https://github.com/fmidue/logic-tasks/issues/46#issuecomment-1612003313

2023-12-12 11:01 UTC, jvoigtlaender commented
... sowie hier: https://github.com/fmidue/logic-tasks/issues/48#issuecomment-1612025336

2023-12-12 11:03 UTC, jvoigtlaender commented
Bzgl. des Festhängens bei Testfällen: kann sein, dass in irgendeinem der Formelgeneratoren (oder so) noch ein unter seltenen Bedingungen zuschlagender Fall von nicht abbrechender Rekursion versteckt ist. 😢

2023-12-12 13:11 UTC, nimec01 commented
Mit 
```
stack repl
> :m + Control.Monad.Output
> :m + Test.QuickCheck
> generate (generateSuperfluousBracketsInst defaultSuperfluousBracketsConfig) >>= \i -> putStrLn (stringWithSuperfluousBrackets i)
```
konnte ich erreichen, was ich wollte. Die Formeln enthielten bis jetzt auch immer mindestens zwei verschiedene Operatoren. 

Ist die Implementation so weit in Ordnung?

2023-12-12 13:22 UTC, jvoigtlaender requested changes

2023-12-12 13:22 UTC, jvoigtlaender commented on src/Trees/Helpers.hs
> +numOfUniqueOpsInSynTree x = num' x []
Da nur binary ops gezählt werden sollen, sollte dies vielleicht auch im Funktionsnamen ausgedrückt werden.

2023-12-12 13:22 UTC, jvoigtlaender commented on src/Trees/Helpers.hs
> +                                                        else 1 + num' sub1 (op:xs) + num' sub2 (op:xs)
Käme hier nicht bei einem Baum wie `Und (Oder X Y) (Oder U V)` heraus, dass drei Operatoren vorkommen, obwohl es nur zwei sind?

2023-12-12 13:27 UTC, jvoigtlaender commented
Zu überlegen wäre noch, ob nicht der Parameter `minUniqueOperators`, bzw. umbenannt vielleicht `minUniqueBinOperators`, sogar in den `SynTreeConfig` Teil wandern könnte (und dann Einbau der Filterung direkt in `genSynTree`), wodurch dann auch andere Aufgabentypen von dieser zusätzlichen Steuerungsmöglichkeit profitieren würden. (Wo diese Steuerungsmöglichkeit nicht gebraucht wird, kann der Parameter ja jeweils auf `0` oder `1` gesetzt werden.)

2023-12-12 13:29 UTC, jvoigtlaender commented
Zum Zeitpunkt eines Merge müsste @owestphal mal sagen, ob es im Moment unproblematisch geht oder lieber bis nach einem eventuellen nächsten Autotool-Deploy gewartet werden sollte (weil Konfigurationstyp-Änderungen ungewünschte Auswirkungen auf im aktuellen Semester bereits gestellte Aufgabeninstanzen haben könnten).

2023-12-12 15:18 UTC, owestphal commented
Änderungen an der Konfiguragtion sollten wenn möglich bis nach dem Semester warten. Sonst bekommen alle Bonusaufgaben rückwirkend neue Instanzen oder funktionieren nicht mehr. Das macht Nachvollzeihen der Fehler für die Studierenden schwierig und die Bonuspunkte als Ganzes sehr undurchsichtig.

2023-12-14 14:18 UTC, nimec01 commented on src/Trees/Helpers.hs
> +numOfUniqueOpsInSynTree x = num' x []
Wurde mit den neusten Commits geändert.

2023-12-14 14:19 UTC, nimec01 commented on src/Trees/Helpers.hs
> +                                                        else 1 + num' sub1 (op:xs) + num' sub2 (op:xs)
Ja, das wurde jetzt mit den neusten Commits behoben.

2023-12-14 14:21 UTC, nimec01 commented
> Zu überlegen wäre noch, ob nicht der Parameter `minUniqueOperators`, bzw. umbenannt vielleicht `minUniqueBinOperators`, sogar in den `SynTreeConfig` Teil wandern könnte (und dann Einbau der Filterung direkt in `genSynTree`), wodurch dann auch andere Aufgabentypen von dieser zusätzlichen Steuerungsmöglichkeit profitieren würden. (Wo diese Steuerungsmöglichkeit nicht gebraucht wird, kann der Parameter ja jeweils auf `0` oder `1` gesetzt werden.)

Ich habe die Logik jetzt entsprechend verschoben. Der Standardwert von `minUniqueBinOperators` liegt jetzt erstmal bei `0`.

2023-12-29 14:46 UTC, jvoigtlaender commented on src/Tasks/SynTree/Config.hs
> +        german "Es sollte eine positive Anzahl an unterschiedlichen Operatoren geben"
`positive` -> `non-negative`, da `0` ja erlaubt wird

2023-12-29 14:48 UTC, jvoigtlaender commented on src/Trees/Helpers.hs
> +numOfUniqueBinOpsInSynTree x = fromIntegral (length (nubBy (==) (ops x)))
`nubBy (==)` wäre einfach `nub`, oder?

Wahrscheinlich merkt sogar `hlint` dies an?

Konkret ist statt `nub` aber fast immer `nubOrd` aus dem `extra` package besser.

2023-12-29 14:49 UTC, jvoigtlaender approved these changes

2023-12-29 14:51 UTC, jvoigtlaender commented
Bis auf die obigen beiden Kleinigkeiten scheint mir dies fertig.

Wegen des Einflusses auf die aktuelle Semester-Instanz muss der Merge aber warten. Wahrscheinlich sollte dann ein geeignetes Label verwendet werden, um diesen Status zu markieren.

2023-12-29 14:58 UTC, jvoigtlaender commented on src/Tasks/SynTree/Config.hs
> +        german "Es sollte eine positive Anzahl an unterschiedlichen Operatoren geben"
Vermutlich wäre es auch noch sinnvoll, gegen ein zu hohes Setzen von `minUniqueBinOperators` vorzugehen. Also etwa `minUniqueBinOperators == 5` wäre ja problematisch, wenn es überhaupt nur `And`, `Or`, `Impl`, `Equi` gibt.

Die tatsächliche Anzahl von Operatoren im Datentyp (um auf etwaige spätere Erweiterungen vorbereitet zu sein) müsste sich durch einen Ausdruck wie `length [ minBound .. maxBound :: BinOp]` "dynamisch" ermitteln lassen.

2023-12-29 16:24 UTC, nimec01 commented
Ich habe die Kleinigkeiten soeben beseitigt. Labeländerung kann ich nicht vornehmen (falls das nochmal geändert werden soll).

2024-01-05 16:30 UTC, jvoigtlaender commented
There are several too-long-lines in the PR.

2024-01-08 13:39 UTC, nimec01 commented
It's fixed now.

2024-01-20 14:42 UTC, merged